MPY_DIR = /home/kkoehler/micropython/
PICO_SDK_PATH = /home/kkoehler/pico/pico-sdk/

MOD = display
SRC = display.c
ARCH = armv6m

include $(MPY_DIR)/py/dynruntime.mk
#include $(PICO_SDK_PATH)/external/pico_sdk_import.cmake
